apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-app
  labels:
    app: document-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : document-service-app
  template:
    metadata:
      labels:
        app: document-service-app
    spec:
      containers:
      - name: document-service-app
        image: malekv1/document-service
        imagePullPolicy: Never
        ports:
          - containerPort: 9002

---

kind: Service
apiVersion: v1
metadata:
  name:  document-service-svc
spec:
  selector:
    app:  document-service-app
  ports:
  - port:  80
    targetPort:  9002