server:
  port: 9002

spring:
  application:
    name : DOCUMENT-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost